version: '3.8'

services:
  # Service 1: Database PostgreSQL
  postgres-db:
    image: postgres:17-alpine
    container_name: ticketing-postgres
    environment:
      POSTGRES_DB: ticketing_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Service 2: Aplikasi Spring Boot
  app:
    build: .
    container_name: ticketing-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/ticketing_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgrespassword
    depends_on:
      - postgres-db

volumes:
  postgres_data: