spring.application.name=backend

# Server Port
server.port=8080

# Database Connection (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/ticketing_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Settings
# update: Otomatis membuat/memperbarui tabel di DB sesuai Entity Java
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop

# Menampilkan query SQL asli di terminal (Bagus untuk belajar & analisa query)
spring.jpa.show-sql=true

# Formatting SQL di terminal agar rapi (tidak menyamping)
spring.jpa.properties.hibernate.format_sql=true

# Dialect PostgreSQL untuk Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


logging.level.org.springframework.web=DEBUG